# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:     
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: "ruff lint"
        files: "^backend/"

      ####### Relevant part below #######

      - id: ruff
        args: ["check", "--select", "I", "--fix"]
        files: "^backend/"

      ####### Relevant part above #######

      - id: ruff-format
        name: "ruff format"
        files: "^backend/"
